/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PagebRouteImport } from './routes/pageb'
import { Route as PageaRouteImport } from './routes/pagea'
import { Route as IndexRouteImport } from './routes/index'

const PagebRoute = PagebRouteImport.update({
  id: '/pageb',
  path: '/pageb',
  getParentRoute: () => rootRouteImport,
} as any)
const PageaRoute = PageaRouteImport.update({
  id: '/pagea',
  path: '/pagea',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pagea': typeof PageaRoute
  '/pageb': typeof PagebRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pagea': typeof PageaRoute
  '/pageb': typeof PagebRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pagea': typeof PageaRoute
  '/pageb': typeof PagebRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pagea' | '/pageb'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pagea' | '/pageb'
  id: '__root__' | '/' | '/pagea' | '/pageb'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PageaRoute: typeof PageaRoute
  PagebRoute: typeof PagebRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pageb': {
      id: '/pageb'
      path: '/pageb'
      fullPath: '/pageb'
      preLoaderRoute: typeof PagebRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagea': {
      id: '/pagea'
      path: '/pagea'
      fullPath: '/pagea'
      preLoaderRoute: typeof PageaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PageaRoute: PageaRoute,
  PagebRoute: PagebRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
