/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PageeRouteImport } from './routes/pagee'
import { Route as PagedRouteImport } from './routes/paged'
import { Route as PagecRouteImport } from './routes/pagec'
import { Route as PagebRouteImport } from './routes/pageb'
import { Route as PageaRouteImport } from './routes/pagea'
import { Route as CubeRouteImport } from './routes/cube'
import { Route as IndexRouteImport } from './routes/index'

const PageeRoute = PageeRouteImport.update({
  id: '/pagee',
  path: '/pagee',
  getParentRoute: () => rootRouteImport,
} as any)
const PagedRoute = PagedRouteImport.update({
  id: '/paged',
  path: '/paged',
  getParentRoute: () => rootRouteImport,
} as any)
const PagecRoute = PagecRouteImport.update({
  id: '/pagec',
  path: '/pagec',
  getParentRoute: () => rootRouteImport,
} as any)
const PagebRoute = PagebRouteImport.update({
  id: '/pageb',
  path: '/pageb',
  getParentRoute: () => rootRouteImport,
} as any)
const PageaRoute = PageaRouteImport.update({
  id: '/pagea',
  path: '/pagea',
  getParentRoute: () => rootRouteImport,
} as any)
const CubeRoute = CubeRouteImport.update({
  id: '/cube',
  path: '/cube',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cube': typeof CubeRoute
  '/pagea': typeof PageaRoute
  '/pageb': typeof PagebRoute
  '/pagec': typeof PagecRoute
  '/paged': typeof PagedRoute
  '/pagee': typeof PageeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cube': typeof CubeRoute
  '/pagea': typeof PageaRoute
  '/pageb': typeof PagebRoute
  '/pagec': typeof PagecRoute
  '/paged': typeof PagedRoute
  '/pagee': typeof PageeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cube': typeof CubeRoute
  '/pagea': typeof PageaRoute
  '/pageb': typeof PagebRoute
  '/pagec': typeof PagecRoute
  '/paged': typeof PagedRoute
  '/pagee': typeof PageeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cube'
    | '/pagea'
    | '/pageb'
    | '/pagec'
    | '/paged'
    | '/pagee'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cube' | '/pagea' | '/pageb' | '/pagec' | '/paged' | '/pagee'
  id:
    | '__root__'
    | '/'
    | '/cube'
    | '/pagea'
    | '/pageb'
    | '/pagec'
    | '/paged'
    | '/pagee'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CubeRoute: typeof CubeRoute
  PageaRoute: typeof PageaRoute
  PagebRoute: typeof PagebRoute
  PagecRoute: typeof PagecRoute
  PagedRoute: typeof PagedRoute
  PageeRoute: typeof PageeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pagee': {
      id: '/pagee'
      path: '/pagee'
      fullPath: '/pagee'
      preLoaderRoute: typeof PageeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paged': {
      id: '/paged'
      path: '/paged'
      fullPath: '/paged'
      preLoaderRoute: typeof PagedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagec': {
      id: '/pagec'
      path: '/pagec'
      fullPath: '/pagec'
      preLoaderRoute: typeof PagecRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pageb': {
      id: '/pageb'
      path: '/pageb'
      fullPath: '/pageb'
      preLoaderRoute: typeof PagebRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagea': {
      id: '/pagea'
      path: '/pagea'
      fullPath: '/pagea'
      preLoaderRoute: typeof PageaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cube': {
      id: '/cube'
      path: '/cube'
      fullPath: '/cube'
      preLoaderRoute: typeof CubeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CubeRoute: CubeRoute,
  PageaRoute: PageaRoute,
  PagebRoute: PagebRoute,
  PagecRoute: PagecRoute,
  PagedRoute: PagedRoute,
  PageeRoute: PageeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
